name: Sound / Code
description: Guillaume's musings

destination:  ../blog-output

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://www.soundcode.co.za'
google_analytics: 'UA-XXXXXXXX-X'

gems:
- jekyll-paginate
- jekyll-asciidoc

asciidoctor:
  attributes:
    - idprefix=_
    - source-highlighter=pygments
    - pygments-css=style
    - imagesdir= /assets/images

# Details for the RSS feed generator
url:            'http://www.soundcode.co.za'
author:         'Guillaume Belrose'

disqus_id: www-soundcode-co-za
org_site: www.soundcode.co.za
org_url: http://www.soundcode.co.za
